apiVersion: v1
kind: Service

metadata:
  name: kubeguardian-backend
  namespace: kubeguardian

spec:
  selector:
    app: kubeguardian-backend

  ports:
  - port: 8000
    targetPort: 8000

  type: ClusterIP